apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    default: true
    secureJsonData:
      token: YourToken
    jsonData:
      organization: YourOrg
      version: Flux
      defaultBucket: YourBucket