{
 "title": "Energy Cost",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Electricity Standing Charges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flexible_tariff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricity_standing_charge\")\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Flexible\"}))\r\n  |> aggregateWindow(every: 1d, fn: mean)"
    },
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker_tariff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricity_standing_charge\")\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Tracker\"}))\r\n  |> aggregateWindow(every: 1d, fn: mean)"
    }
   ]
  },
  {
   "title": "Gas Standing Charges",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flexible_tariff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gas_standing_charge\")\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Flexible\"}))\r\n  |> aggregateWindow(every: 1d, fn: mean)"
    },
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker_tariff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gas_standing_charge\")\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Tracker\"}))\r\n  |> aggregateWindow(every: 1d, fn: mean)"
    }
   ]
  },
  {
   "title": "Electricity Unit Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flexible_tariff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricity_unit_rate\")\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Flexible\"}))\r\n  |> aggregateWindow(every: 1d, fn: mean)"
    },
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker_tariff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"electricity_unit_rate\")\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Tracker\"}))\r\n  |> aggregateWindow(every: 1d, fn: mean)"
    }
   ]
  },
  {
   "title": "Gas Unit Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flexible_tariff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gas_unit_rate\")\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Flexible\"}))\r\n  |> aggregateWindow(every: 1d, fn: mean)"
    },
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tracker_tariff\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gas_unit_rate\")\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Tracker\"}))\r\n  |> aggregateWindow(every: 1d, fn: mean)"
    }
   ]
  },
  {
   "title": "Electricity Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity_cost\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flexible_tariff_cost\")\r\n  |> map(fn: (r) => ({_value: r._value / 100.0, _time: r._time, _field: \"Flexible\"}))\r\n"
    },
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"electricity_cost\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tracker_tariff_cost\")\r\n  |> map(fn: (r) => ({_value: r._value / 100.0, _time: r._time, _field: \"Tracker\"}))"
    }
   ]
  },
  {
   "title": "Gas Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_cost\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flexible_tariff_cost\")\r\n  |> map(fn: (r) => ({_value: r._value / 100.0, _time: r._time, _field: \"Flexible\"}))"
    },
    {
     "query": "from(bucket: \"Energy\")\r\n  |> range(start: -30d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gas_cost\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tracker_tariff_cost\")\r\n  |> map(fn: (r) => ({_value: r._value / 100.0, _time: r._time, _field: \"Tracker\"}))"
    }
   ]
  }
 ]
}